# Generated by Django 4.1.4 on 2024-03-08 13:20

from django.db import migrations, models

import core.basemodels


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="status",
            name="icon",
            field=core.basemodels.IconField(),
        ),
        migrations.AddField(
            model_name="status",
            name="is_default",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddConstraint(
            model_name="status",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("board", "is_default"),
                name="unique_default_status_per_board",
            ),
        ),
    ]
