# Generated by Django 5.0.3 on 2024-03-20 14:11

import core.basemodels
import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="status_default",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="board_default_status",
                to="core.status",
            ),
        ),
        migrations.AddField(
            model_name="status",
            name="icon",
            field=core.basemodels.IconField(
                blank=True,
                choices=[
                    ("fa-gift", "fa-solid fa-gift"),
                    ("fa-star", "fa-regular fa-star"),
                    ("fa-solid-star", "fa-solid fa-star"),
                    ("fa-rocket", "fa-solid fa-rocket"),
                    ("fa-circle-exclamation", "fa-solid fa-circle-exclamation"),
                    ("fa-exclamation", "fa-solid fa-exclamation"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="footer",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="suggestion",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.status",
            ),
        ),
    ]
