# Generated by Django 4.1.4 on 2023-08-08 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="suggestion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="comments",
                to="core.suggestion",
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="status",
                to="core.board",
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="suggestion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="votes",
                to="core.suggestion",
            ),
        ),
    ]
