# Generated by Django 4.1.4 on 2023-10-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_comment_suggestion_alter_status_board_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="author_email",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="author_id",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="author_name",
        ),
        migrations.RemoveField(
            model_name="suggestion",
            name="author_email",
        ),
        migrations.RemoveField(
            model_name="suggestion",
            name="author_id",
        ),
        migrations.RemoveField(
            model_name="suggestion",
            name="author_name",
        ),
        migrations.AddField(
            model_name="board",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="status",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suggestion",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vote",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
