# Generated by Django 4.1.4 on 2024-03-19 14:50

import core.basemodels
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_status_icon_status_is_default_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="icon",
            field=core.basemodels.IconField(
                blank=True,
                choices=[
                    ("fa-gift", "fa-solid fa-gift"),
                    ("fa-star", "fa-regular fa-star"),
                    ("fa-solid-star", "fa-solid fa-star"),
                    ("fa-rocket", "fa-solid fa-rocket"),
                    ("fa-circle-exclamation", "fa-solid fa-circle-exclamation"),
                    ("fa-exclamation", "fa-solid fa-exclamation"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
