# Generated by Django 4.1.4 on 2024-02-08 08:20

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                help_text=customers.models.PasswordValidator.get_help_text,
                max_length=128,
                validators=[customers.models.PasswordValidator.validate],
                verbose_name="password",
            ),
        ),
    ]
